#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DietCalculator.Droid.Resource", IsApplication=true)]

namespace DietCalculator.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int gender_array = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int levelOfActivity_array = 2131099649;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int blue = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int grey = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int highlight = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int lightgrey = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int transparent = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int white = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int thickblueline = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int thinblueline = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int AgeHeader = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int GenderHeader = 2131165187;
			
			// aapt resource value: 0x7f07001d
			public const int LevelOfActivityHeader = 2131165213;
			
			// aapt resource value: 0x7f070002
			public const int ageText = 2131165186;
			
			// aapt resource value: 0x7f07002a
			public const int bmiRatioResultText = 2131165226;
			
			// aapt resource value: 0x7f070029
			public const int bmiRatioTextView = 2131165225;
			
			// aapt resource value: 0x7f07001f
			public const int calculateButton = 2131165215;
			
			// aapt resource value: 0x7f070022
			public const int caloriesPerDayResultText = 2131165218;
			
			// aapt resource value: 0x7f070021
			public const int caloriesPerDayTextView = 2131165217;
			
			// aapt resource value: 0x7f070015
			public const int chHeader = 2131165205;
			
			// aapt resource value: 0x7f07002c
			public const int cholestrolRatioResultText = 2131165228;
			
			// aapt resource value: 0x7f07002b
			public const int cholestrolRatioTextView = 2131165227;
			
			// aapt resource value: 0x7f070017
			public const int cholestrolText = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int cholestrolTextView = 2131165206;
			
			// aapt resource value: 0x7f070026
			public const int fatResultText = 2131165222;
			
			// aapt resource value: 0x7f070025
			public const int fatTextView = 2131165221;
			
			// aapt resource value: 0x7f070004
			public const int genderSpinner = 2131165188;
			
			// aapt resource value: 0x7f070019
			public const int hdlText = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int hdlTextView = 2131165208;
			
			// aapt resource value: 0x7f070009
			public const int heightText = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int heightTextView = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int hipsLayout = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int hipsText = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int hipsTextView = 2131165198;
			
			// aapt resource value: 0x7f070005
			public const int hwHeader = 2131165189;
			
			// aapt resource value: 0x7f070014
			public const int idealBMIText = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int idealBMITextView = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int idealWeightText = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int idealWeightTextView = 2131165201;
			
			// aapt resource value: 0x7f070030
			public const int idealWeihtResultText = 2131165232;
			
			// aapt resource value: 0x7f07002f
			public const int idealWeihtResultTextView = 2131165231;
			
			// aapt resource value: 0x7f070010
			public const int iwbHeader = 2131165200;
			
			// aapt resource value: 0x7f070024
			public const int leanBodyMassResultText = 2131165220;
			
			// aapt resource value: 0x7f070023
			public const int leanBodyMassTextView = 2131165219;
			
			// aapt resource value: 0x7f07001e
			public const int levelOfActivitySpinner = 2131165214;
			
			// aapt resource value: 0x7f07001a
			public const int neckHeader = 2131165210;
			
			// aapt resource value: 0x7f07001c
			public const int neckText = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int neckTextView = 2131165211;
			
			// aapt resource value: 0x7f070020
			public const int resultsHeader = 2131165216;
			
			// aapt resource value: 0x7f070000
			public const int spinnerTextView = 2131165184;
			
			// aapt resource value: 0x7f07002e
			public const int waistHeightRatioResultText = 2131165230;
			
			// aapt resource value: 0x7f07002d
			public const int waistHeightRatioTextView = 2131165229;
			
			// aapt resource value: 0x7f070028
			public const int waistHipsRatioResultText = 2131165224;
			
			// aapt resource value: 0x7f070027
			public const int waistHipsRatioTextView = 2131165223;
			
			// aapt resource value: 0x7f07000c
			public const int waistText = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int waistTextView = 2131165195;
			
			// aapt resource value: 0x7f070007
			public const int weightText = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int weightTextView = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int whHeader = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int diet_spinner_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Results = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
